CONFIG = {
    "emoji": "🤖",
    "title": "Hệ thống Bot",
    "group_by_parent": False,
    "modules": {
        "bot_info/main.py": {"emoji": "♨️", "title": "Bot", "cmds": ["bot", "del", "xoa", "delete"]},
        "thue_bot/main.py": {"emoji": "❖", "title": "Thuê Bot", "cmds": ["thuebot", "create", "lock", "unlock", "list_bots", "reset", "change_prefix", "active", "bot_info", "share", "update", "setbox"]},
        "func_share/main.py": {"emoji": "💌", "title": "Share code", "cmds": ["share"]},
        "func_friend/main.py": {"emoji": "❖", "title": "Friend", "cmds": ["block", "kb", "kbgr", "unblock", "xkb"]},
        "func_autosend/main.py": {"emoji": "⏳", "title": "Tin nhắn tự động", "cmds": ["autosend"]},
        "details/main.py": {"emoji": "❖", "title": "Details", "cmds": ["details"]},
        "func_allan/main.py": {"emoji": "❖", "title": "Allan", "cmds": ["all", "lmao"]},
        "func_disbox/main.py": {"emoji": "❖", "title": "Disbox", "cmds": ["disbox"]},
        "func_kickall/main.py": {"emoji": "❖", "title": "Kickall", "cmds": ["kickall"]},
        "func_leave/main.py": {"emoji": "❖", "title": "Leave", "cmds": ["leave_group"]},
        "func_welcome/main.py": {"emoji": "👋", "title": "Welcome & Bye", "cmds": ["welcome", "bye"]},
        "func_group_link/main.py": {"emoji": "🔗", "title": "Link nhóm", "cmds": ["link"]},
        "func_pin/main.py": {"emoji": "❖", "title": "Pinterest", "cmds": ["pin"]},
        "func_spamsms/main.py": {"emoji": "❖", "title": "Spamsms", "cmds": ["sms"]},
        "func_spam_call/main.py": {"emoji": "❖", "title": "Spamcall", "cmds": ["spamcall"]},
        "func_src/main.py": {"emoji": "❖", "title": "Src", "cmds": ["src"]},
        "func_tdm/main.py": {"emoji": "❖", "title": "Tdm", "cmds": ["tdm"]},
        "join_gr/main.py": {"emoji": "❖", "title": "Join", "cmds": ["spam"]},
        "join_gr1/main.py": {"emoji": "❖", "title": "Join1", "cmds": ["join", "join1"]},
        "spamjoin/main.py": {"emoji": "❖", "title": "Spamjoin", "cmds": ["spamjoin"]},
        "treo/main.py": {"emoji": "❖", "title": "Treo", "cmds": ["treo"]},
        "uptime/main.py": {"emoji": "❖", "title": "Uptime", "cmds": ["uptime"]},
        "func_duyet/main.py": {"emoji": "🔑", "title": "Duyệt quyền & QL key", "cmds": ["duyet", "unduyet", "capkey", "huykey", "listkey", "duyetmedia", "duyetanh", "duyetnude", "unduyetnude"]},
        "func_group_lock/main.py": {"emoji": "🔒", "title": "Khóa nhóm", "cmds": ["lock", "lockgroup", "unlockgroup"]},
        "tiktok/main.py": {"emoji": "🎵", "title": "TikTok", "cmds": ["tiktok", "downtik", "tt", "tiktokinfo", "in4tiktok", "tiktoksearch"]}
    }
}
